defaults: &defaults
  host: 'redis'
  port: 6379

development:
  <<: *defaults

test:
  host: <%= ENV['WERCKER_REDIS_HOST'] || 'localhost' %>
  port: 6379

staging:
  <<: *defaults

production:
  <<: *defaults